version: '3'
services:
  app-discovery:
    build:
      context: ./micro-discovery
      dockerfile: Dockerfile
    container_name: discovery
    volumes:
     - "./logfiles/micro-discovery:/logs"
    restart: always
    ports:
     - "8081:8081"

  app-auth:
    build:
      context: ./micro-auth
      dockerfile: Dockerfile
    container_name: auth
    depends_on: 
      - app-discovery
    environment:
      spring.jpa.hibernate.ddl-auto: update
      spring.datasource.url: jdbc:mysql://localhost:3306/USERSERVICE?useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    volumes:
     - "./logfiles/micro-auth:/logs"
    restart: always
    ports:
     - "8082:8082"

  app-core:
    build:
      context: ./micro-core
      dockerfile: Dockerfile
    container_name: core
    environment:
      eureka.client.serviceUrl.defaultZone: http://admin:pass@app-discovery:8081/eureka/
    depends_on: 
      - app-discovery
    volumes:
     - "./logfiles/micro-core:/logs"
    restart: always
    ports:
     - "8084:8084"

  app-func:
    build:
      context: ./micro-func
      dockerfile: Dockerfile
    container_name: func
    depends_on: 
      - app-discovery
    volumes:
     - "./logfiles/micro-func:/logs"
    restart: always
    ports:
     - "8085:8085"

  app-gateway:
    build:
      context: ./micro-gateway
      dockerfile: Dockerfile
    container_name: gateway
    depends_on: 
      - app-discovery
    volumes:
     - "./logfiles/micro-gateway:/logs"
    restart: always
    ports:
     - "10000:10000"
