version: '3'
services:
  app-discovery:
    build:
      context: ./micro-discovery
      dockerfile: Dockerfile
    container_name: discovery
    volumes:
     - "./logfiles/micro-discovery:/logs"
    restart: always
    ports:
     - "8081:8081"
    networks: 
     - my-network

  app-auth:
    build:
      context: ./micro-auth
      dockerfile: Dockerfile
    container_name: auth
    depends_on: 
      - app-discovery
    environment:
      spring.jpa.hibernate.ddl-auto: update
      spring.datasource.url: jdbc:mysql://localhost:3306/USERSERVICE?useSSL=false
      spring.datasource.username: root
      spring.datasource.password: root
      spring.datasource.driver-class-name: com.mysql.jdbc.Driver
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    volumes:
     - "./logfiles/micro-auth:/logs"
    restart: always
    ports:
     - "8082:8082"
    networks: 
     - my-network

  networks:
    my-network :
