eureka:
  server:
    maxThreadsForPeerReplication: 0
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
      enableSelfPreservation: false
  instance:
    preferIpAddress: true
    hostname: ${springboot.app.name:discovery-service}
  serviceUrl:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/