eureka:
  server:
    maxThreadsForPeerReplication: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  instance:
      hostname: 127.0.0.1
      preferIpAddress: true
  serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/