eureka:
  server:
    maxThreadsForPeerReplication: 0
  client:
    healthcheck:
      enabled: true
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  instance:
      preferIpAddress: true
      #hostname: 127.0.0.1
      statusPageUrlPath: ${server.servletPath}:${server.port}/info
      healthCheckUrlPath: ${server.servletPath}:${server.port}/health
      statusPageUrl: http://${eureka.hostname}:${server.port}/info
      healthCheckUrl: http://${eureka.hostname}:${server.port}/health
      homePageUrl: http://${eureka.hostname}:${server.port}/
  serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/